### ISSUE TITLE
Remove class name which is present multiple times, will only remove one of the occurrences

### ISSUE THREAD

**Issue by frostaxis** [tobua/svg-classlist-polyfill#1]
Example using the code from the remove function:
```
var className = "c";
var classList = "a b c c"
var newClassList = classList.replace(
              new RegExp('(\\s|^)'.concat(className, '(\\s|$)'), 'g'),
              '$2'
            )
console.log(newClassList)
```

Prints: a b c
Expected: a b

**Comment by tobua** [comment]
Hey @frostaxis, thanks for reporting the issue. You're right, it won't remove multiple of the same class when side-by-side. After fixing the tests in the plugin, I've added a fix by running the regex multiple times. New version of the plugin with the fix is released.

Please let me know if that works for you?
